### ISSUE TITLE
Override Existing VM

### ISSUE THREAD

**Issue by Cescendo** [lamw/ghettoVCB#103]
We have 2 datastores ( 1 SSD, where everything happens and 2 HDD in a RAID as a backup if the SSD fails)
Our problem is that, only 1 vm fits on our HDD. Is it somehow possible to add an override feature?
Would really appreciate it!

BR
Chris

**Comment by it64-markus** [comment]
What exactly do you mean? You could use '-f $PATH/to/vmlist.conf' to backup only certain VMs.

HTH
Markus
