### ISSUE TITLE
Only one backup per day result in strange errors

### ISSUE THREAD

**Issue by heutger** [lamw/ghettoVCB#106]
I test each rollout, so I do a manual backup with the same arguments as in the cronjob. I just found out, that if the same day the cronjob is doing the backup (with rotation and amount of 3 backups), it result in an error to backup vmdk file, there are two mails regarding the error (so I first thought of a time adjustment by ntp and missing or not working script locks). Always I was able to do it manually again, so I tried my own lock scheme without success and then just tried to wait one day, if backup will work now and it did. Shouldn't t be possible to overwrite a backup e.g. from 9 o clock in the morning with 10 o clock pm in the evening or have them both in rotation? Does rotation depend on date and not on count?

**Comment by lamw** [comment]
Is this still an issue?

**Comment by heutger** [comment]
I‘m sorry, I dunno, as my Intel NUC has been broken and I stopped then my home server project and moved to the cloud.
