### ISSUE TITLE
Only backing up vmx file on VM with NVME controller and disk.

### ISSUE THREAD

**Issue by punksux** [lamw/ghettoVCB#109]
I am on ESXi 6.5, and I set up a new VM with an NVME controller and hard disk. When I try to back the VM up with ghettoVCB, it only backs up the vmx file, and completes successfully in a few seconds. All of my other VMs that are on SCSI controllers will back up correctly. I am using the newest version of ghettoVCB from git.

**Comment by lamw** [comment]
You'll need to see what the NVMe Controller shows up in the VMX file, then update https://github.com/lamw/ghettoVCB/blob/master/ghettoVCB.sh#L416 which should fix the problem. As you can see right now its looking for scsi, ide or sata controllers

**Comment by 11chrisadams11** [comment]
Thank you. That worked. 
I added a pull request #110 with the change.
