### ISSUE TITLE
Why backup recovered machines take so long?

### ISSUE THREAD

**Issue by takenek** [lamw/ghettoVCB#111]
Hello i do test:
1. Install new server with 20GB HDD.
2. Backup this server - takes 20 sec because of SSD drivers.
3. Delete original machine
4. Recover Original machine from backup.
5. Backup recovered machine taken 3 minutes.

Why after backup recover machine takes so long?
Best Regards
TaKeN

**Comment by hkaiserl** [comment]
have you checked if your restored file is in the same format as it was before?
(thin vs think)?

**Comment by takenek** [comment]
How to check that ?
