### ISSUE TITLE
syntax error: invalid syntax with ghettoUI at line 226 when using on esxi 6.5

### ISSUE THREAD

**Issue by squadri** [lamw/ghettoVCB#117]
We are encountering issue while running "python ghettoUI"  showing File "ghettoUI", line 226
print "ghettoUI Menu %s" % (version) on Esxi 6.5 Host.

Syntax error: invalid syntax

However, when we run the same on Esxi 6.0 , it runs fine with no error.

Appreciate all useful help.

![capture](https://user-images.githubusercontent.com/3611415/27260198-80781b80-542e-11e7-8aab-ca13cc864c0f.JPG)

**Comment by squadri** [comment]
Any idea.s...... no response yet

**Comment by lamw** [comment]
I don't know what ghettoUI is ... this might be a 3rd party solution using my script. May want to ping the author of that tool

**Comment by ffejtable** [comment]
Just to add, ESXi 6.5 has python 3.x.  ghettoUI hasnt been updated in 8 years and was written for older versions of ESXi that only had python 2.x.  The change of the print statement to a function is one of the man changes that makes python2 scripts generally incompatible with python3.

As William mentioned, this is not an issue with ghettoVCB.
