### ISSUE TITLE
Temporary NFS mount fails on 6.5.0

### ISSUE THREAD

**Issue by matute8** [lamw/ghettoVCB#118]
I think it's related to line 781: 
if [[ ${ESX_RELEASE} == "5.5.0" ]] || [[ ${ESX_RELEASE} == "6.0.0" ]] ; then

What worked for me is adding 6.5 release (that behaves like 5.5 and 6.0)
if [[ ${ESX_RELEASE} == "5.5.0" ]] || [[ ${ESX_RELEASE} == "6.0.0" ]] || [[ ${ESX_RELEASE} == "6.5.0" ]] ; then

Hope this helps and it can be merged in the great script. Sorry it's my first time in Git and I'm not sure how should I proceed and if I should or not upload changes to the script.

**Comment by tdeleeuw** [comment]
Didn't saw your pull request. I made a similar change but using "${VER}" == "6" to cover both 6.0.0 and 6.5.0

**Comment by lamw** [comment]
This has been resolved with latest merge https://github.com/lamw/ghettoVCB/commit/e12a3564998eed59fce0b5c0415d371a1d4ae085
