### ISSUE TITLE
FTP/WebDAV upload?

### ISSUE THREAD

**Issue by christoph-puppe** [lamw/ghettoVCB#123]
Hi

as my provider offers free backup space via CIFS, webDAV or FTP, would it be possible to add that?

**Comment by lamw** [comment]
No plans, especially as ESXi has limited access to connect to things like CIFS/FTP

**Comment by ffejtable** [comment]
ESXi provides limited connectivity to such services, and writing something to do that (in my opinion) is beyond the scope of this project.  

If you are backing up to a location that is accessible to other machines (and I would hope you are), such as a remote NAS device, that device may have "cloud" backup options.

If you provide more details on your scenario I may be able to help.
