### ISSUE TITLE
ghettoVCB fails cloning on NFS datastore

### ISSUE THREAD

**Issue by ekis** [lamw/ghettoVCB#139]
I am trying to backup my VMs from an ESXi 6.5.0a to a NAS datastore via NSF and it fails with output ```info: ERROR: Unable to backup win7 due to error in VMDK backup!```

Debug log reveals this line failing
```
/sbin/vmkfstools -i "/vmfs/volumes/Master/VMs/win7/win7.vmdk" -d "thin" "/vmfs/volumes/QNAP-Datastore/win7/win7-
2018-01-06_23-32-21/win7.vmdk"
```
Trying to execute that line directly from the shell terminates with the following exception -> ```Clone: 9% done.Failed to clone disk: The file specified is not a virtual disk (15).``` Googling the problem got me nowehere closer to solution. 

Dry run completes successfully.

Here is the df output proving the datastore is successfully mounted:
```
[root@esxilab:/opt/ghettovcb/bin] df -h
Filesystem   Size   Used Available Use% Mounted on
NFS41       10.1T   4.9T      5.2T  49% /vmfs/volumes/QNAP-Datastore
VMFS-5     894.0G 207.5G    686.5G  23% /vmfs/volumes/Master
vfat       285.8M 205.8M     80.0M  72% /vmfs/volumes/563c181d-bd5a4b1c-4275-a0369fa16850
vfat       249.7M 143.9M    105.8M  58% /vmfs/volumes/d0a199e4-87369e0e-0358-e2c5409b80f1
vfat       249.7M 144.0M    105.8M  58% /vmfs/volumes/3d848ee5-7f285f5a-be99-7491472f2aea
```
I've proven that I can read and write from the NFS share.

Also, here is the config file I am using:
```
VM_BACKUP_VOLUME=/vmfs/volumes/QNAP-Datastore
DISK_BACKUP_FORMAT=thin
VM_BACKUP_ROTATION_COUNT=3
POWER_VM_DOWN_BEFORE_BACKUP=0
ENABLE_HARD_POWER_OFF=0
ITER_TO_WAIT_SHUTDOWN=3
POWER_DOWN_TIMEOUT=5
ENABLE_COMPRESSION=0
VM_SNAPSHOT_MEMORY=0
VM_SNAPSHOT_QUIESCE=0
ALLOW_VMS_WITH_SNAPSHOTS_TO_BE_BACKEDUP=0
ENABLE_NON_PERSISTENT_NFS=0
UNMOUNT_NFS=0
NFS_SERVER=192.168.20.110
NFS_VERSION=nfs41
NFS_MOUNT=/ESXiDataStore
NFS_LOCAL_NAME=ESXiDataStore
NFS_VM_BACKUP_DIR=ESXiDataStore
SNAPSHOT_TIMEOUT=15
EMAIL_ALERT=0
EMAIL_LOG=0
EMAIL_SERVER=auroa.primp-industries.com
EMAIL_SERVER_PORT=25
EMAIL_DELAY_INTERVAL=1
EMAIL_TO=auroa@primp-industries.com
EMAIL_ERRORS_TO=
EMAIL_FROM=root@ghettoVCB
WORKDIR_DEBUG=0
VM_SHUTDOWN_ORDER=
VM_STARTUP_ORDER=
VMDK_FILES_TO_BACKUP="win7.vmdk"

```
What am I missing here?

Any help is greatly appreciated.

**Comment by bircoe** [comment]
Check permissions, first time I ran a backup to an NFS share it failed with a similar message, as a test I just did the usual chmod -R 777 to the backup dir and the next test was successful.

**Comment by ekis** [comment]
@bircoe As you had suggested, it was a permissions problem - however, I fixed it simply with reverting back to NFS3 and disabling NFS41 altogether. I have no idea what was the issue with NFS4, I probably misconfigured something stupid.

Thanks.
