### ISSUE TITLE
When running backup from interactive shell, getting a "ash: missing ]]"

### ISSUE THREAD

**Issue by codeskipper** [lamw/ghettoVCB#140]
Only happens when running interactive in shell during test run, not in log file or e-mailed log

Found the bug already, it's a single missing whitespace in the if statement for the sanity check for VM_BACKUP_ROTATION_COUNT, right before the closing ]].  
Here's a snippet of output when doing a dryrun test of a backup list on cli:

<pre><code>
[root@ESXi04:/vmfs/volumes/5a8da94a-fceefb70-f042-9c8e9958815a/script/backup/da-ghettoVCB] ./ghettoVCB.sh -g ghettoVCB.conf -l /vmfs/volumes/datastore1/log/da-ghettoVCB/2018-03-12_18-12-05-log-ghettoVCB-backu
p-list-cron-daily.txt -f ghettoVCB-backup-list-cron-daily.txt -d dryrun
<b>ash: missing ]]</b>
2018-03-12 18:12:25 -- info: ============================== ghettoVCB LOG START ==============================
</pre></code>

Will be submitting a pull request for this one.

**Comment by jp83** [comment]
I think this is the same as #145 and was fixed in 97363ce49cd3706061d306b8e23d653281fb951b on May 16.  However, I don't think this has been rolled into either of the vib bundles dated April 28.  I just re-installed and have the same problem, can the vibs be updated?  Not sure how to hack the fix locally, I can't seem to overwrite write privileges to edit the .sh file directly on my esxi host as root.

**Comment by lamw** [comment]
Hi @jp83 

Apologies, I've not been able to keep up with all the updates. I've just re-built the VIB/offline bundle from the current repo. I've not had a chance to test, but its there now. Can you let me know if you're having any issues

**Comment by jp83** [comment]
I'm not sure what I'm doing wrong.  I've uninstalled and reinstalled the new version.  I've double checked the hash listed contains the space before brackets fix.  I also visually looked at line 1525 of /opt/ghettovcb/bin/ghettoVCB.sh and see the fix.  However, by the time my cron runs overnight I still get the error in my email.  I come back in the morning and don't see the space anymore.  Does uninstalled/reinstalling the vib require a reboot to make it stick or something?  It's probably an issue on my side, but I'm confused.

esxcli software vib get -n=ghettoVCB
virtuallyGhetto_bootbank_ghettoVCB_1.0.0-0.0.0
   Name: ghettoVCB
   Version: 1.0.0-0.0.0
   Type: bootbank
   Vendor: virtuallyGhetto
   Acceptance Level: CommunitySupported
   Summary: [Fling] ghettoVCB VM backup and restore script
   Description: bdb08ad547ec8686019e4eba75b226b97b21fa78
   ReferenceURLs: ghettoVCB|https://github.com/lamw/ghettoVCB
   Creation Date: 2018-05-29

ls -lart /opt/ghettovcb/bin/ghettoVCB.sh
-r-xr-xr-x    1 root     root         71366 Apr 28 13:43 /opt/ghettovcb/bin/ghettoVCB.sh

(I think this date should be like May 16)

**Comment by lamw** [comment]
It depends on how you update the VIB, its possible its still caching. Best thing is to simply remove the VIB and then reboot. After that, re-install the new VIB. I'd also recommend just doing a manual backup of a VM, just to make sure it works as expected before running the cronjob

**Comment by jp83** [comment]
That fixed it for me.  I'm not the original poster, but you can probably close this issue.
