### ISSUE TITLE
Log entry for snapshot found is a info level even though it result in an error

### ISSUE THREAD

**Issue by GMZwinge** [lamw/ghettoVCB#148]
https://github.com/lamw/ghettoVCB/blob/bdb08ad547ec8686019e4eba75b226b97b21fa78/ghettoVCB.sh#L1040

The backup sometime gives error, but it's not always easy to figure out what the error is when looking at the logs. One example is when VM has a snapshot and snapshots are not being consolidated. This result in a backup error, but only a single line like this reveal the source of the error:

`<DateTimeStamp> -- info: Snapshot found for <...>, backup will not take place`

The log entry should be at error level since is results in an error.

**Comment by lamw** [comment]
Good suggestion, just fixed this
