### ISSUE TITLE
Backups don't appear to be valid?

### ISSUE THREAD

**Issue by ronlaws86** [lamw/ghettoVCB#154]
after letting the backup run over night, to validate them this morning i tried to import them on a non-production ESXi server and they come up as "Invalid" and have to be removed from the Interactive shell, making a new VM and adding the existing disk appears to be unbootable also.

**Comment by ronlaws86** [comment]
Issue Resolved. 
This was actually due to a VM Version Mismatch, the source of the backups was newer (V6.7) than the test server (6.5), editing the .vmx 
and replacing 
**virtualHW.version = "14"**
with 
_virtualHW.version = "13"_
solves the problem.

Unsure why the first attempt to attach the vmdk to a new vm failed, the machines fired up fine after this trick.

**Comment by ffejtable** [comment]
Good candidate for an enhancement request..  It's possible to check the HW version with the ESX version being restored to, and to print a friendlier message.  Not sure pull requests are getting added to the main branch for this project anymore.
