### ISSUE TITLE
support script build / remove VIB Author depenencies

### ISSUE THREAD

**Issue by hi-ko** [lamw/ghettoVCB#159]
Using the VIB Author to build the ghettoVCB VIB is a cumbersome overhead which also prevents automated builds / tests. Instead I created a simple shell script which is independant from redhat to build the the VIB. Please check [create-vib.sh](https://github.com/ecm4u/ghettoVCB/blob/master/create-vib.sh) using a [descriptor.xml.tmpl](https://github.com/ecm4u/ghettoVCB/blob/master/descriptor.xml.tmpl) file.

UPDATE: I changed the script to be more or less generic for file deployments stored in a stage dir.
The file structure in this repo should reflect the structure of the vib (/opt/ghettovcb/...) stored in a named subdir to avoid unnecessary config/boiler code. The descriptor.xml should be also stored here as it is or prepared as a template like in the example above.

**Comment by lamw** [comment]
Not sure what you mean by cumbersome overhead ... for CI/CD or automated builds, simply use the VIB Author Docker Container which is used by number of folks and that'll provide you with a way to build VIB using official VMware Tools

**Comment by hi-ko** [comment]
I'm aware of your docker image but we try to avoid docker / pipeline on our jenkins if we don't need it. I think it's an overkill to install/maintain docker just to compress and sign files into a vib archive. The ar command is available on any *ix box. Additionally it looks like the vib-author tool [is deprecated](https://labs.vmware.com/flings/vib-author/comments).
My demand is just to move the files into relative paths to _also_ support simple generic scripts. If you also store your descriptor.xml here in this project anybody could create the the vib if required either by docker, vibautor or by simple script.

**Comment by lamw** [comment]
vibauthor is the "official" method for creating ESXi VIB/Offline Bundles and although I get `ar` can be used, I personally can't recommend it given our official stance. Although the tool is deprecated, it still the only official tool that customers can use to construct their own custom VIB/Offline Bundles and the docker container should make it easy for anyone to consume. 

In addition to incorporating the build scripts directly within the repo https://github.com/lamw/ghettoVCB/tree/master/build (which I use these scripts to create the official ghettoVCB releases), also I also implemented your suggestion from #158 and have moved everything to `/opt/ghettovcb` (thank you for that great suggestion)
