### ISSUE TITLE
Problem with non persistent NFS on ESXi 6.7

### ISSUE THREAD

**Issue by EGruber01** [lamw/ghettoVCB#169]
We graded up our servers to ESXi 6.7.0. After upgrading non persistent nfs did not work with error 'can't create volume'(or something like that) and 'Permission denied'. I figured out the mount command used in ghettoVCB.sh:
vim-cmd hostsvc/datastore/nas_create <storage_name> nfs <remote_share> 0 <server>
does not work anymore, for which reason ever. I replaced it with:
  esxcfg-nas -a <storage_name> -o <server> -s <remote_share>
now my non persistent backup works again :-)
regards E. Gruber

**Comment by NotAProfessionalDeveloper** [comment]
That's strange. That part of the code:
```
${VMWARE_CMD} hostsvc/datastore/nas_create "${NFS_LOCAL_NAME}" "${NFS_VERSION}" "${NFS_MOUNT}" 0 "${NFS_SERVER}"
```
(https://github.com/lamw/ghettoVCB/blame/master/ghettoVCB.sh#L898)

seems to coincide with how `nas_create` is called
```
Usage: nas_create name nfsVersion remotePath readonly remoteHostNames
```

**Comment by NotAProfessionalDeveloper** [comment]
I've now actually tried using ESXi 6.7 and it works flawlessly.
Probably you were using an outdated version of ghettoVCB which didn't already have the 5.5+ fixes introduced 7 years ago?
This issue should be closed.

**Comment by lamw** [comment]
Please reopen if this is still an issue
