### ISSUE TITLE
option -g does not work on esxi 6.7 update2

### ISSUE THREAD

**Issue by softwallch** [lamw/ghettoVCB#170]
Hello
if I start the backup with -g the following error message comes

[root@esx1:/vmfs/volumes/5d249b4c-ac99a6c8-1ab6-4c536216e4e2/ghettoVCB-master] ./ghettoVCB.sh -m DLS -d dryrun -g ghettoVCB.conf
./ghettoVCB.sh: source: line 413: ghettoVCB.conf: not found
[root@esx1:/vmfs/volumes/5d249b4c-ac99a6c8-1ab6-4c536216e4e2/ghettoVCB-master] ls -l
total 4112
-rw-r--r--    1 root     root          2616 Jul  9 14:04 README.md
-rwxr-xr-x    1 root     root         17559 Jul  9 14:04 ghettoVCB-restore.sh
-rw-r--r--    1 root     root          1025 Jul  9 14:15 ghettoVCB-restore_vm_configuration
-rw-r--r--    1 root     root           309 Jul  9 14:04 ghettoVCB-restore_vm_restore_configuration_template
-rw-r--r--    1 root     root           356 Jul  9 14:04 ghettoVCB-vm_backup_configuration_template
-rw-r--r--    1 root     root           797 Jul  9 14:04 ghettoVCB.conf
-rwxr-xr-x    1 root     root         71957 Jul  9 14:04 ghettoVCB.sh
-rw-r--r--    1 root     root         23751 Jul  9 14:04 vghetto-ghettoVCB-offline-bundle.zip
-rw-r--r--    1 root     root         21204 Jul  9 14:04 vghetto-ghettoVCB.vib

is this problem known?

**Comment by afiz** [comment]
Try this...

`-g ./ghettoVCB.conf`

**Comment by lenny76** [comment]
same problem for me
with the solution of @afiz  It works!
thanks
