### ISSUE TITLE
Restoring UEFI VM Failing

### ISSUE THREAD

**Issue by vampire337** [lamw/ghettoVCB#171]
I have an ESXi 6.7.0U2 host which uses ghettoVCB to back up nightly. I've noticed now with a couple VMs that when I go to restore the VM using the ghettoVCB-restore.sh script, the result is a non-bootable VM stuck at the Windows boot loader screen:
![image](https://user-images.githubusercontent.com/3717803/62726776-fe809600-b9e5-11e9-8a18-4cfe4443dfe8.png)

This appears to apply only to my newer VMs created using EFI instead of BIOS for boot. Virtualization Based Security (VBS) is not enabled, nor is Secure Boot, for the VM I'm attempting to restore. I've now seen this with a Windows Server 2016 VM and a Photon OS 3.0 (Linux) VM. Is this a known issue with a workaround, or do I need to find another backup system because I have started using UEFI?

**Comment by lamw** [comment]
Related to #214
