### ISSUE TITLE
 VMDK on different datastore not found - ghettoVCB not honoring workingDir in .vmx

### ISSUE THREAD

**Issue by kdeiss** [lamw/ghettoVCB#176]
This is similar to issue#26

Because the user reporting this issue was not working anymore with ghetto he could not answer the question whether still is a problem.

Yes is still a problem!

We have a VM with two disks, one on a ssd, second one in a different datastore. In the vmx the disk file names are not stored with their full path (how it is without manually added fileSearchPath and/or workingDir). In this case the paths are defined in fileSearchPath and/or workingDir variable.

ghettoVCB will only backup the VMDK from the ssd (where the .vmx is stored). And throw an error:

WARNING: A physical RDM \"${SOURCE_VMDK}\" was found for ${VM_NAME}, which will not be backed up"

Reason ist that the grep into the vmdk exit with 2 (file not found):
For debug purpose I patched the script to see whats going on.

2019-09-19 10:14:07 -- info: grep vmfsPassthroughRawDeviceMap /vmfs/volumes/ssd-1/TS-Neuaufbau/TS-Neuaufbau_2.vmdk returned 2
2019-09-19 10:14:07 -- info: ERROR: error in backing up of "/vmfs/volumes/ssd-1/TS-Neuaufbau/TS-Neuaufbau_2.vmdk" for WEBER-TSERVER

Unfortunately I can't fix this, sorry.

Klaus

**Comment by Gerard-CK** [comment]
I have the same issue. Can this be re-opened?
