### ISSUE TITLE
ESXi 6.7 not working crontab

### ISSUE THREAD

**Issue by nzncngz** [lamw/ghettoVCB#185]
Hi all,
I backup manual with GhettoVCB but It don't working with crontab.
gheettoVCB locations on vmware;

[root@localhost:/vmfs/volumes/5c7ce51e-b8b762f8-c0f0-b06ebf3aaf75/ghettoVCB] ls
README.md                                            ghettoVCB-restore_vm_restore_configuration_template  vghetto-ghettoVCB-offline-bundle.zip
backup3                                              ghettoVCB-vm_backup_configuration_template           vghetto-ghettoVCB.vib
ghettoVCB-backup.log                                 ghettoVCB.conf                                       vms_to_restore
ghettoVCB-restore.sh                                 ghettoVCB.sh
[root@localhost:/vmfs/volumes/5c7ce51e-b8b762f8-c0f0-b06ebf3aaf75/ghettoVCB] pwd
/vmfs/volumes/datastore1/ghettoVCB

----------------------------------------------------------------
I am editting  /etc/rc.local.d/local.sh
#!/bin/sh

# local configuration options

# Note: modify at your own risk!  If you do/use anything in this
# script that is not part of a stable API (relying on files to be in
# specific places, specific tools, specific output, etc) there is a
# possibility you will end up with a broken system after patching or
# upgrading.  Changes are not supported unless under direction of
# VMware support.

# Note: This script will not be run when UEFI secure boot is enabled.

echo "26 13 * * * /vmfs/volumes/datastore1/ghettoVCB/ghettoVCB.sh -f /vmfs/volumes/datastore1/ghettoVCB/backup3 > /vmfs/volumes/datastore1/ghettoVCB//ghettoVCB-backup.log" >> /var/spool/cron/crontabs/root
kill -9 `cat /var/run/crond.pid `
/usr/lib/vmware/busybox/bin/busybox crond

exit 0

-----------------------------------------------
/var/spool/cron/crontabs/root file not include crontab my rules
[root@localhost:/vmfs/volumes/5c7ce51e-b8b762f8-c0f0-b06ebf3aaf75/ghettoVCB] cat /var/spool/cron/crontabs/root
#min hour day mon dow command
1    1    *   *   *   /sbin/tmpwatch.py
1    *    *   *   *   /sbin/auto-backup.sh
0    *    *   *   *   /usr/lib/vmware/vmksummary/log-heartbeat.py
*/5  *    *   *   *   /bin/hostd-probe.sh ++group=host/vim/vmvisor/hostd-probe/stats/sh
00   1    *   *   *   localcli storage core device purge
40   12   *   *   *   /etc/rc.local.d/local.sh

**Comment by NotAProfessionalDeveloper** [comment]
You could at least have the decency of correctly quoting your messages and configuration files and whatnot using the code tag (<>)

**Comment by lamw** [comment]
crontab certainly functions in all versions of ESXi, if this is an issue, please reopen
