### ISSUE TITLE
Email subject

### ISSUE THREAD

**Issue by axel338** [lamw/ghettoVCB#187]
Hello,

Good job and thank you for developing this app.

I would like to know if we have the possibility to change the subject of the email sent.Because I have several backups and I don't know which one was done.

Here is the command I use

`/opt/ghettovcg/ghettoVCB.sh -f /etc/ghettovcb/list1 -g /etc/ghettovcb/ghettoVCB.conf`

And this is my conf file
```
VM_BACKUP_VOLUME=/vmfs/volumes/1870ecea-5374c27d/backup-ghettoVCB-ESXI1
DISK_BACKUP_FORMAT=thin
VM_BACKUP_ROTATION_COUNT=3
POWER_VM_DOWN_BEFORE_BACKUP=0
ENABLE_HARD_POWER_OFF=0
ITER_TO_WAIT_SHUTDOWN=3
POWER_DOWN_TIMEOUT=5
ENABLE_COMPRESSION=0
VM_SNAPSHOT_MEMORY=0
VM_SNAPSHOT_QUIESCE=0
ALLOW_VMS_WITH_SNAPSHOTS_TO_BE_BACKEDUP=0
ENABLE_NON_PERSISTENT_NFS=0
UNMOUNT_NFS=0
SNAPSHOT_TIMEOUT=25
EMAIL_ALERT=1
EMAIL_LOG=1
EMAIL_SERVER=mail.example.org
EMAIL_SERVER_PORT=25
EMAIL_DELAY_INTERVAL=1
EMAIL_USER_NAME=
EMAIL_USER_PASSWORD=
EMAIL_TO=group@example.org
EMAIL_ERRORS_TO=group@example.org
EMAIL_FROM=ESXI1-ghettoVCB@example.org
WORKDIR_DEBUG=0
VM_SHUTDOWN_ORDER=
VM_STARTUP_ORDER=

```

**Comment by NotAProfessionalDeveloper** [comment]
From what I can see the email subject is hardcoded as
`Subject: ghettoVCB - $(hostname -s) ${FINAL_STATUS}\r\n`
What information would you like to see in the subject?

In your case one would probably have to add the possibility of specifying a "job name" when `-f` is being used.
