### ISSUE TITLE
"Error" is not a valid loglevel

### ISSUE THREAD

**Issue by thegushi** [lamw/ghettoVCB#199]
Hey there,

We've had backups silently erroring for months, and had to add our own debugs in to figure out where.  The problem is in this line:

logger "error" "Snapshot found for ${VM_NAME}, backup will not take place\n"

However, that's not one of the log types you check for to put it in the logs.  This is the ONLY usage of the loglevel "error" anywhere in the entire script, and should probably be changed to "info".

**Comment by thegushi** [comment]
Bump.

**Comment by NotAProfessionalDeveloper** [comment]
Since you've managed to add your own debugs why not submit a patch? ;-)

**Comment by thegushi** [comment]
Literally "change one word in the script" hasn't seen attention for five months.  

Why would I believe that undergoing the effort to generate a patch and produce a pull request (13 outstanding) would do any better?

**Comment by NotAProfessionalDeveloper** [comment]
Then why complain in the first place if you know already?

**Comment by thegushi** [comment]
Looks like this has been fixed in the meantime.
