### ISSUE TITLE
Make releases in the releases section

### ISSUE THREAD

**Issue by spitfire** [lamw/ghettoVCB#201]
Can you start using https://github.com/lamw/ghettoVCB/releases for your builds? That way people would be able to be notified when one is released. I've noticed you have your builds straight in the repository, but I believe this approach would be more convenient.

**Comment by lamw** [comment]
Very good point. When this repo was originally ported from VMTN, it was all manually managed locally on my system and Git/Github wasn't something I was too familiar with. I've not had much spare time to really manage the day to day aspects and enhancing some of these basics things. 

In any case, just added quick update to support ESXi 7.0 Update 1 and enabled Releases https://github.com/lamw/ghettoVCB/releases/tag/latest
