### ISSUE TITLE
Error in VMDK backup

### ISSUE THREAD

**Issue by ubenmackin** [lamw/ghettoVCB#202]
Recently I have started having some VMs that are failing to backup. The logs will look something like:

```
Destination disk format: VMFS thin-provisioned
Cloning disk '/vmfs/volumes/VMSSD/Greylog/Greylog-0.vmdk'...
Clone: 100% done.Failed to clone disk: No such device or address (393225).

2020-10-08 02:18:41 -- info: ERROR: error in backing up of "/vmfs/volumes/VMSSD/Greylog/Greylog-0.vmdk" for Greylog
2020-10-08 02:18:43 -- info: Removing snapshot from Greylog ...
2020-10-08 02:18:43 -- info: Backup Duration: 4.62 Minutes
2020-10-08 02:18:43 -- info: ERROR: Unable to backup Greylog due to error in VMDK backup!

2020-10-08 02:18:43 -- info: ###### Final status: ERROR: No VMs backed up! ######
```

I'll watch the backup, and the Clone percentage will count up all the way to 100%, then it sits there for 5-10 seconds, and then gives the error. If I try rerunning the backup, it will usually fail again. But if I manually run

vmkfstools -i Greylog-0.vmdk -d thin /vmfs/volumes/backups/VMBACKUPS/Greylog/Greylog-0.vmdk

That will run just fine. So I am not sure what is happening that ghettoVCB is thinking things fail, because the clone command seems to work out just fine.

**Comment by davidmarquesneves** [comment]
Read my suggestion at:
https://github.com/lamw/ghettoVCB/issues/203

**Comment by ubenmackin** [comment]
So I finally got around to that, but I am unsure exactly what is causing the error:

```
DISKLIB-VMFS  : "/vmfs/volumes/547f273f-aa9b631e-0000-000000000000/VMBACKUPS/Greylog/Greylog-2020-10-23_00-20-34/Greylog-0-flat.vmdk" : open successful (33554433) size = 34359738368, hd = 0. Type 3
DISKLIB-VMFS  : "/vmfs/volumes/547f273f-aa9b631e-0000-000000000000/VMBACKUPS/Greylog/Greylog-2020-10-23_00-20-34/Greylog-0-flat.vmdk" : closed.
DISKLIB-VMFS  : "/vmfs/volumes/547f273f-aa9b631e-0000-000000000000/VMBACKUPS/Greylog/Greylog-2020-10-23_00-20-34/Greylog-0-flat.vmdk" : open successful (33288) size = 34359738368, hd = 1646347. Type 3
DISKLIB-DSCPTR: Opened [0]: "Greylog-0-flat.vmdk" (0x8208)
DISKLIB-LINK  : Opened '/vmfs/volumes/547f273f-aa9b631e-0000-000000000000/VMBACKUPS/Greylog/Greylog-2020-10-23_00-20-34/Greylog-0.vmdk' (0x8208): vmfs, 67108864 sectors / 32 GB.
DISKLIB-LIB   : Opened "/vmfs/volumes/backups/VMBACKUPS/Greylog/Greylog-2020-10-23_00-20-34/Greylog-0.vmdk" (flags 0x8208, type vmfs).
DDB: "longContentID" = "c5ad7376296bc37228e8169a07240546" (was "3258f1153f61fee47f7a80a5fffffffe")
DDB: "virtualHWVersion" = "4" (was "14")
DISKLIB-LINK  : DiskLinkNativeVmfsCloneExisting: Failed to create native clone. (24).
DISKLIB-LIB_CLONE   : Failed to create native clone on destination handle : The specified feature is not supported by this version (24).
OBJLIB-FILEBE : FileBEIoctl: ioctl operation IOCTLCMD_VMFS_XCOPY_TRANSFER_SIZE(3077) failed on '/vmfs/volumes/56007cbd-6a075f60-0000-000000000000/Greylog/Greylog-0-flat.vmdk' : Inappropriate ioctl for device (1638402)
Clone: 100% done.
2020-10-23 00:25:32 -- info: ERROR: error in backing up of "/vmfs/volumes/VMSSD/Greylog/Greylog-0.vmdk" for Greylog
```

**Comment by ubenmackin** [comment]
So I made one change, and that was to mount my backup datastore as nfs3 instead of nfs4. This seems t have solved the issue. Not sure why it is, but posting this in case anyone else runs into a similar issue.

**Comment by rohanpatilcalsoft** [comment]
We are facing same issue using below command.
 vmkfstools -i /vmfs/volumes/Testsmallclone/Testsmallclone.vmdk /vmfs/volumes/Test
/cDestVastClone_temp2/csCloned_disk45.vmdk -v verbose
and Below is the error 
Option --adaptertype is deprecated and hence will be ignored
DISKLIB-VMFS  : "/vmfs/volumes/75811298-7e9ef824/Testsmallclone/Testsmallclone-flat.vmdk" : open successful (269) size = 799957026560, hd = 0. Type 3
DISKLIB-VMFS  : "/vmfs/volumes/75811298-7e9ef824/Testsmallclone/Testsmallclone-flat.vmdk" : closed.
DISKLIB-VMFS  : "/vmfs/volumes/75811298-7e9ef824/Testsmallclone/Testsmallclone-flat.vmdk" : open successful (14) size = 536870912, hd = 32182885. Type 3
Destination disk format: VMFS thin-provisioned
Cloning disk '/vmfs/volumes/TestVastClone/Testsmallclone/Testsmallclone.vmdk'...
DISKLIB-LIB_CREATE   : CREATE: "/vmfs/volumes/TestVastClone/cDestVastClone_temp2/csCloned_disk46.vmdk" -- vmfs capacity=0 (0 bytes) adapter=lsilogic info=cowGran=0 allocType=1 objType=file policy='' spifSpecList=''
DISKLIB-LIB_CLONE   : Failed to clone disk using Object Cloning
DISKLIB-LIB_CREATE   : CREATE: "/vmfs/volumes/TestVastClone/cDestVastClone_temp2/csCloned_disk46.vmdk" -- vmfs capacity=1048576 (512 MB) adapter=lsilogic info=cowGran=1 allocType=1 objType=file policy='' spifSpecList=''
DISKLIB-LIB_CREATE   : CREATE: Creating disk backed by 'file'
Clone: 19% done.DISKLIB-DSCPTR: "/vmfs/volumes/TestVastClone/cDestVastClone_temp2/csCloned_disk46.vmdk" : creation successful.
DISKLIB-VMFS  : "/vmfs/volumes/75811298-7e9ef824/cDestVastClone_temp2/csCloned_disk46-flat.vmdk" : open successful (33554433) size = 799957051184, hd = 0. Type 3
DISKLIB-VMFS  : "/vmfs/volumes/75811298-7e9ef824/cDestVastClone_temp2/csCloned_disk46-flat.vmdk" : closed.
DISKLIB-VMFS  : "/vmfs/volumes/75811298-7e9ef824/cDestVastClone_temp2/csCloned_disk46-flat.vmdk" : open successful (33288) size = 536870912, hd = 28996198. Type 3
DDB: "longContentID" = "33776a296200b66b9e7855bffffffffe" (was "fa2b07be399350295e74f4b2fffffffe")
Partial data received. fd [10] remaining [8] error [25] [Inappropriate ioctl for device]
Unable to receive data from vaai-nasd [Inappropriate ioctl for device]
DISKLIB-LINK  : DiskLinkNativeVmfsCloneExisting: Failed to create native clone. (318).
DISKLIB-LIB_CLONE   : Failed to create native clone on destination handle : Unknown error (318).
OBJLIB-FILEBE : FileBEIoctl: ioctl operation IOCTLCMD_VMFS_XCOPY_TRANSFER_SIZE(3077) failed on '/vmfs/volumes/75811298-7e9ef824/Testsmallclone/Testsmallclone-flat.vmdk' : Inappropriate ioctl for device (1638402)
Clone: 100% done.DISKLIB-VMFS  : "/vmfs/volumes/75811298-7e9ef824/cDestVastClone_temp2/csCloned_disk46-flat.vmdk" : closed.
DISKLIB-VMFS  : "/vmfs/volumes/75811298-7e9ef824/Testsmallclone/Testsmallclone-flat.vmdk" : closed.

AIOMGR-S : stat o=7 r=12 w=0 i=23 br=196608 bw=0
OBJLIB-LIB: ObjLib cleanup done.
WORKER: asyncOps=0 maxActiveOps=0 maxPending=0 maxCompleted=0
