### ISSUE TITLE
7.0 Update 1 / 7.0.1

### ISSUE THREAD

**Issue by schtebo** [lamw/ghettoVCB#204]
Hi,
updated my ESX to 7.0 Update 1.
ghettovcb stops running with following message.
Would be great if you could fix this.
Thank you very much.

Message:
`/bin/sh /opt/ghettovcb/bin/ghettoVCB.sh -a -g /etc/ghettovcb/ghettoVCB.conf`
Logging output to "/tmp/ghettoVCB-2020-10-10_06-53-18-272784.log" ...
You're not running ESX(i) 3.5, 4.x, 5.x & 6.x!

ESX Version:
`vmware -v | awk '{print $3}'`
7.0.1

`vmware -v`
VMware ESXi 7.0.1 build-16850804

**Comment by lamw** [comment]
Fixed. You can also grab the latest VIB/Offline Bundle from either within the repo or now from `Releases` section https://github.com/lamw/ghettoVCB/releases/tag/latest

**Comment by schtebo** [comment]
thank you :)
