### ISSUE TITLE
Remove adaptertype from VMKFSTOOLS calls

### ISSUE THREAD

**Issue by kubedzero** [lamw/ghettoVCB#208]
While running ghettoVCB, I see multiple instances of the following:

```
Cloning disk '/vmfs/volumes/970PRO/W10LTSB1607-VM/W10LTSB1607-VM_1.vmdk'...
Clone: 96% done.
Option --adaptertype is deprecated and hence will be ignored
```

Searching for "adapter" in the script, I am led to https://github.com/lamw/ghettoVCB/blob/master/ghettoVCB.sh#L1209 and https://github.com/lamw/ghettoVCB/blob/master/ghettoVCB.sh#L1212

Both lines seem to call VMKFSTOOLS, which for me is located at `/bin/vmkfstools` (and unfortunately does not print out a version number). When running its help information, I see `-a --adaptertype [deprecated]` which aligns with the `-a "${ADAPTER_FORMAT}"` usage in the script and the deprecation warning in the logs.

I'm not sure if the binaries in older versions of ESXi also have this flag deprecated (https://github.com/lamw/ghettoVCB/blob/master/ghettoVCB.sh#L307 seems to suggest support back to version 3.5.0) but once support for old versions is dropped or confirmation is made that this flag isn't necessary in old versions, it might be worth removing this from the script to avoid those log lines every time a disk is backed up. Or maybe a conditional checking the version number, and versions that don't need it can have it removed? 

Thanks!

**Comment by lamw** [comment]
Resovled
