### ISSUE TITLE
Install offline bundle not working on 7.0.1 build-17168206

### ISSUE THREAD

**Issue by takenek** [lamw/ghettoVCB#212]
Hello
I try Install offline bundle and i get error:

[root@esx05:/tmp] wget https://raw.githubusercontent.com/lamw/ghettoVCB/master/vghetto-ghettoVCB-offline-bundle.zip
Connecting to raw.githubusercontent.com (151.101.112.133:443)
vghetto-ghettoVCB-of 100% |*********************************************************************************************************************************************************************************************| 23830  0:00:00 ETA
[root@esx05:/tmp] ls -al
total 32
drwxrwxrwt    1 root     root           512 Dec  2 09:37 .
drwxr-xr-x    1 root     root           512 Dec  2 09:36 ..
-rw-r--r--    1 root     root         23830 Dec  2 09:37 vghetto-ghettoVCB-offline-bundle.zip
[root@esx05:/tmp] esxcli software vib install -d /tmp/vghetto-ghettoVCB-offline-bundle.zip
 [VibValidationError]
 VIB virtuallyGhetto_bootbank_ghettoVCB_1.0.0-0.0.0 violates extensibility rule checks: ['(line 26: col 0) Element vib failed to validate content']
 Please refer to the log file for more details.

Best Regards
TaKeN

**Comment by lamw** [comment]
You need to specify `-f` option. See instructions at https://github.com/lamw/ghettoVCB
