### ISSUE TITLE
nvram is not backed up

### ISSUE THREAD

**Issue by daMihe** [lamw/ghettoVCB#214]
NVRAM is needed for restore as it contains relevant information about boot in UEFI systems (that needs to be repaired via a rescue CD or manual selection of the bootfile). Choosing Windows as guest OS typically creates a UEFI system. Classic BIOS VMs do not have this problem as all relevant data is contained in the first sectors of the disk.

The nvram file is linked inside the vmx-file using the key "nvram".

**Comment by lamw** [comment]
Yup, this makes sense. I'm wondering if nvram should simply be backed up for ALL VMs or just `efi` based VMs? 

If its the latter, we can determine if a VM is configured for EFI by checking if `firmware = "efi"` is present

**Comment by daMihe** [comment]
It also makes sense to backup nvram on classic systems as further settings are stored there. One example is that VMwares default settings refer a Floppy, even if none is configured in the VM. I‘ve already seen several times a Linux is trying to probe that non existent drive. That is not critical, but it‘s avoidable. And it‘s an if less 😉. 

I would expect a nvram always existing (never seen a running VM without), but i don‘t know the vmx-spec in that point.
