### ISSUE TITLE
Backup stopped with ESXi-7.0.2

### ISSUE THREAD

**Issue by sw08023** [lamw/ghettoVCB#227]
Seems like ghettoVCB stopped working after ESXi v7.0.2 upgrade

**Comment by lamw** [comment]
It didn't stop ... but rather each new major ESXi release version must be explicitly to the script in case there are issues. 

You can update the following line and add "7.0.2" and you can verify the basic functionality
https://github.com/lamw/ghettoVCB/blob/master/ghettoVCB.sh#L311

**Comment by sw08023** [comment]
Perfect, thank you. updated and it is up and running now. Cheers

**Comment by Antoine1-byte** [comment]
Hi,

I understand the fix (that's a start) and tried to realized it but unfortunately, facing a permission issue on the script...

Is there any workaround to be able to edit the script as recommended?

Thanks and Regards
