### ISSUE TITLE
Support for version 7.0.2

### ISSUE THREAD

**Issue by marco-vaz** [lamw/ghettoVCB#235]
Hi all,

Please add support to version 7.0.2

.........
    case "${ESX_VERSION}" in
            7.0.0|7.0.1)          VER=7; break;;
        6.0.0|6.5.0|6.7.0)    VER=6; break;;
        5.0.0|5.1.0|5.5.0)    VER=5; break;;
        4.0.0|4.1.0)          VER=4; break;;
        3.5.0|3i)             VER=3; break;;
        *)              echo "You're not running ESX(i) 3.5, 4.x, 5.x & 6.x!"; exit 1; break;;
    esac
.............

**Comment by kubedzero** [comment]
#230 addresses this, just waiting for the PR to be merged.

**Comment by elect0r** [comment]
Also remember the check at line 906. I also ran into that issue because I use a NFS mount for backup.

**Comment by k4y53r** [comment]
Do you have estimate to PR?
Regards...

**Comment by NotAProfessionalDeveloper** [comment]
@k4y53r  Good god if it's that urgent, just modify the script yourself... see https://github.com/lamw/ghettoVCB/pull/230/files

**Comment by k4y53r** [comment]
Hi, i've just want to know so eval if i should wait for your official package or try to make myself for first time (not urgent, don't bother about it....)

I'll try to build new offline vib following your docs, thanks and regards

**Comment by lamw** [comment]
7.0 U2 & U3 is already in release
