### ISSUE TITLE
Datastore not found. and cronjob not running at all?

### ISSUE THREAD

**Issue by nostartbutrings** [lamw/ghettoVCB#242]
Hi,

I have a mounted NFS volume where backups are stored (mounted in my ESXi 7.0.2).
If I run a backup from SSH console the VM will be backedup'ed to that NFS share, that's working. But I get some "Datastore not found." messages - what is that?

The next thing is, that the backup job is not run from a cronjob at all. No logs in '/var/log/syslog.log', no ghettoVCB log
The cronjob is inserted in '/var/spool/cron/crontabs/root'.
The cronjob will be recreated after a reboot.

Did I miss something like activating the crond in ESXi? Where can I find more info about the issue (logs, ...)? 

Best regards, Alex

**Comment by nostartbutrings** [comment]
Hi,
so i was able to fix my things:
"Datastore not found." messages: I mounted my NFS volume within ESXi webinterface permanently as a storage and removed all NFS settings in ghettoVCB.conf. Now the messages are gone since ghettoVCB stores its backups on a "local" volume (where NFS volume is mounted)

Cronjob: 
in ESXi 7.0.2 the command to (re-)start crond is no longer '/bin/busybox crond' but '/usr/lib/vmware/busybox/bin/busybox crond'.
Additionally I send any outputs from the kill command to /dev/null to prevent interruption of the script due to failed kill command: '/bin/kill $(cat /var/run/crond.pid) **> /dev/null 2>&1**'

 Perhaps the documentation should be updated for this things.

Best regards, Alex

**Comment by lamw** [comment]
Thanks for the feedback, I've updated the documentation to reflect these suggestions for ESXi 7.x
