### ISSUE TITLE
Support for version 7.0.3

### ISSUE THREAD

**Issue by takenek** [lamw/ghettoVCB#246]
Hey,
There is new version of esxi :-)

[root@esx01:~] uname -a
VMkernel esx01.taken.pl 7.0.3 #1 SMP Release build-18644231 Sep 17 2021 09:16:16 x86_64 x86_64 x86_64 ESXi

Best Regards
TaKeN

**Comment by pmhausen** [comment]
I already added this pull request:
https://github.com/lamw/ghettoVCB/pull/247

**Comment by takenek** [comment]
Thanks, i just checked and working good. All servers backup without issue.
