### ISSUE TITLE
VMDK on different datastore not found - ghettoVCB not honoring fileSearchPath in .vmx

### ISSUE THREAD

**Issue by mikek70** [lamw/ghettoVCB#26]
We have a VM with two disks, one in the VM directory, one in a different datastore. In the vmx the disk file names are not stored with their full path, but the paths are set in the fileSearchPath variable.

ghettoVCB can only backup the VMDK in the VM directory.

Here the relevant lines from the .vmx file:

scsi0:0.fileName = "uranus ST2008.64.R2.vmdk"
scsi0:2.fileName = "uranus ST2008.64.R2_2.vmdk"
fileSearchPath = "/vmfs/volumes/5144d529-e22c7624-dff7-001517919b4e/uranus;."

I can enter the full path as the scsi0:2.fileName and do a backup, but the next time I try to do a backup, the full path already has been overwritten by the system again.

**Comment by mikek70** [comment]
I can't say, since I am no longer using ghettoVCB in my new company, sorry!

**Comment by NotAProfessionalDeveloper** [comment]
Maybe related to #176
