### ISSUE TITLE
ADAPTER_FORMAT create error on second vm

### ISSUE THREAD

**Issue by gbin2265** [lamw/ghettoVCB#266]
If you have more than one vm , and ADAPTER_FORMAT is filled in in the conf file, you will have double -a -a when the 2nd vm is backed up

ADAPTER_FORMAT=buslogic in the conf file 
for the 1st vm it is "-a buslogic", for the 2nd vm it is "-a -a buslogic"

Output DEBUG
+ echo -e '2022-07-20 20:41:08 -- debug: /sbin/vmkfstools -i "/vmfs/volumes/.../name.vmdk" -a -a buslogic -d thin "/vmfs/volumes/.../name.vmdk"'

Output when i do 'sh -x ./ghettoVCB.sh :

+ + '[['tail -n '-a buslogic' -f ]]
 /tmp/ghettoVCB.work/ghettovcb.UP1ZKz
+ ADAPTER_FORMAT='-a -a buslogic'

And also ... 
eval /sbin/vmkfstools -i '"${SOURCE_VMDK}"' '-a -a buslogic' '-d thin' '"${DESTINATION_VMDK}"'

I've removed the ADAPTER_FORMAT option in the conf file and everything works.

VERSION = 2021_10_20_1
ESX_VERSION=7.0.3 (VCENTER)

Regards,
Geert

**Comment by thraxarious** [comment]
This is the same as issue #264. Removing the ADAPTER_FORMAT in config fixes both. But the script might need fixing to sense if the errant entry is not removed from the call if the adapter type is depreciated.
