### ISSUE TITLE
ESXI 8.0 error when attempting to install

### ISSUE THREAD

**Issue by minez0** [lamw/ghettoVCB#275]
Testing ESXI 8.0 (in VMware Workstation) and am receiving the following error when trying to install:

    [root@localhost:~] esxcli software vib install -v /vmfs/volumes/data/vghetto-ghettoVCB.vib -f --dry-run
    [ProfileValidationError]
    In ImageProfile (Updated) ESXi-8.0.0-20513097-standard, the payload(s) in VIB virtuallyGhetto_bootbank_ghettoVCB_1.0.0-0.0.0 does not have sha-256 gunzip checksum. This will prevent VIB security verification and secure boot from functioning properly. Please remove this VIB or please check with your vendor for a replacement of this VIB
    Please refer to the log file for more details.

Is ESXI 8.0 not fully supported as yet? Not sure what might be the underlying cause for the checksum issue?

**Comment by RobertWojtowicz** [comment]
I have the same problem, I can't install on ESXi version 8.0 :(

**Comment by lamw** [comment]
Unfourntately due to changes in VIB packaging for vSphere 8, the current 7.x-based VIBs which are created from deprecated and removed VIB Author is not compatible. There's no workaround other than manually downloading the ghettoVCB* files and placing them on ESXi host. Do note, they will not persist and so it is recommended to store the scripts on a persist storage volume (VMFS/NFS)

**Comment by RobertWojtowicz** [comment]
Any chance there will be an "official on github" version for ESXi 8 ?

**Comment by lamw** [comment]
Sadly there won't be since there's no other way to package up these VIBs as this requires VIB packaging tools that have since been updated to support all requirements/changes

**Comment by RobertWojtowicz** [comment]
@l

> Unfourntately due to changes in VIB packaging for vSphere 8, the current 7.x-based VIBs which are created from deprecated and removed VIB Author is not compatible. There's no workaround other than manually downloading the ghettoVCB* files and placing them on ESXi host. Do note, they will not persist and so it is recommended to store the scripts on a persist storage volume (VMFS/NFS)

unfortunately it does not work, in general sh script do not want to execute :(, I get the information -sh: Operation not permitted
