### ISSUE TITLE
changing the backup path naming convention

### ISSUE THREAD

**Issue by robina80** [lamw/ghettoVCB#283]
hi all,

so ive done my first ever backup using ghetto vcb and so far so good

all my backups ive saved to 

/vmfs/volumes/datastore1/backup

but when it creates the backup it saves the name as "vm_name-yyyy-mm-dd"

/vmfs/volumes/datastore1/backup/vm_name/vm_name-yyyy-mm-dd

is there anyway i can change this please

thanks,
rob

**Comment by robina80** [comment]
Anyone?

**Comment by robina80** [comment]
Bump...

**Comment by Fighter456** [comment]
You can modify the source code of `ghettoVCB.sh` by yourself and your own risk:
https://github.com/lamw/ghettoVCB/blob/588d8f9c44496eb635ea165f8fce80003493eedd/ghettoVCB.sh#L174
https://github.com/lamw/ghettoVCB/blob/588d8f9c44496eb635ea165f8fce80003493eedd/ghettoVCB.sh#L1095

What is the motivation behind this plan?

**Comment by robina80** [comment]
hi @Fighter456 

lets say i want to restore from a backup, as all my backup vms get backed up to a different datastore, what i normally do is copy the backup vm from my backup datastore to my main datastore where i run all my live vms from

once copied i click the vmx file and "register vm in the inventory" i then can play the vm and its up and running

but in the main datastore files, instead of saying the vm_name wont it say vm_name+date, if so i dont want this behaviour

thanks,
rob

**Comment by Fighter456** [comment]
Then I recommend using `ghettoVCB-restore.sh` instead of copying the files from the backup datastore to the main datastore.

The script takes care about the display name of the virtual machine.
