### ISSUE TITLE
Update build script to support VIB creation for ESXi 8.x

### ISSUE THREAD

**Issue by lamw** [lamw/ghettoVCB#291]
ESXi 8.x changes the format of a VIB and the vibauthor tool can no longer be used as it doesn't output the required SHA256 hash. However, the change looks to be trivial and thanks to https://github.com/w2c/letsencrypt-esxi/commit/9ec56ba0ff4bd7fb85a7e8a96bb7feac2e6412ab for working example

**Comment by jhg03a** [comment]
Relates to #281
