### ISSUE TITLE
installing the vib file

### ISSUE THREAD

**Issue by robina80** [lamw/ghettoVCB#293]
hi all,

ive installed the vib file and i got the below so all good

esxcli software vib install -v /vmfs/volumes/datastore1/vghetto-ghettoVCB.vib -f
Installation Result
   Message: Operation finished successfully.
   Reboot Required: false
   VIBs Installed: virtuallyGhetto_bootbank_ghettoVCB_1.0.0-0.0.0
   VIBs Removed:
   VIBs Skipped:

but now where do i find the ghetto vcb script to start a backup?

thanks,
rob

**Comment by lamw** [comment]
The script is installed under `/opt/ghettovcb/bin` and the config is stored under `/opt/ghettovcb`

**Comment by lamw** [comment]
To list all VIB installed: `esxcli software vib list` and to uninstall: `esxcli software vib remove -n <vibname>`

**Comment by robina80** [comment]
@lamw how do i see if the offline bundle is installed

**Comment by lamw** [comment]
same command as above :) These are basic ESXi commands BTW, has nothing to do with ghettoVCB

**Comment by robina80** [comment]
> same command as above :) These are basic ESXi commands BTW, has nothing to do with ghettoVCB

so even installing the zip is a vib is to uninstall the zip version exactly the same command

**Comment by lamw** [comment]
Yes, its just packaging format but ends up in same place

**Comment by robina80** [comment]
thanks @lamw
