### ISSUE TITLE
Calculated digest at EOF does not match expected result

### ISSUE THREAD

**Issue by kamilosgit** [lamw/ghettoVCB#299]
esxcli software vib install -v /vghetto-ghettoVCB.vib -f
 [InstallationError]
 Calculated digest at EOF does not match expected result: 07d3fbf45049ba932a2f06e590adfcf268a3e4036be56c8dcec82c79b611bd92 calculated, 4c235dce439ffdf02c877849b1247b3adeb113ce38e3a0d26c08be018c7ea56b expected.
       vibs = virtuallyGhetto_bootbank_ghettoVCB_1.0.0-0.0.0
 Please refer to the log file for more details.

**Comment by sudo-memo** [comment]
> I have the same problem, can anyone update the digests? Thanks!

I was seeing the same issue installing the new vib on my old ESXi 6.X host, I ended up just installing the previous vib 'ghettoVCB - 2021_10_20' to get it working as I don't need the ESXi 8.x support anyways. Not sure if this applied to you since idk what version you're running.

**Comment by kamilosgit** [comment]
> > I have the same problem, can anyone update the digests? Thanks!
> 
> I was seeing the same issue installing the new vib on my old ESXi 6.X host, I ended up just installing the previous vib 'ghettoVCB - 2021_10_20' to get it working as I don't need the ESXi 8.x support anyways. Not sure if this applied to you since idk what version you're running.

Thanks man!
