### ISSUE TITLE
8.0U2 --> ESX(i) Version not supported!

### ISSUE THREAD

**Issue by WernerHel** [lamw/ghettoVCB#304]
I've downloaded the latest version and include it in 8.0U2 (with vmware autodeploy).
But get a message that the version is not supported.
Is 8.0U2 not supported?

**Comment by lamw** [comment]
Each ESXi major release and Update release has different version (as expected) and until its confirmed to function, its not added to list which you can see https://github.com/lamw/ghettoVCB/blob/master/ghettoVCB.sh#L312 

You can adjust script to add `8.0.2` and since U1 worked, I don't expect anything different. If you can confirm it works, happy to make the change and do a quick release update

**Comment by WernerHel** [comment]
Thank you,

Backup is working with 8.0.2!

Werner
________________________________
Van: William Lam ***@***.***>
Verzonden: Friday, September 29, 2023 1:04:26 PM
Aan: lamw/ghettoVCB ***@***.***>
CC: Werner Hellinghuizer ***@***.***>; Author ***@***.***>
Onderwerp: Re: [lamw/ghettoVCB] 8.0U2 --> ESX(i) Version not supported! (Issue #304)


Each ESXi major release and Update release has different version (as expected) and until its confirmed to function, its not added to list which you can see https://github.com/lamw/ghettoVCB/blob/master/ghettoVCB.sh#L312

You can adjust script to add 8.0.2 and since U1 worked, I don't expect anything different. If you can confirm it works, happy to make the change and do a quick release update

**Comment by mvander** [comment]
Can confirm also.

**Comment by lamw** [comment]
Merged code and published an updated release https://github.com/lamw/ghettoVCB/releases/tag/2023_09_29

**Comment by WernerHel** [comment]
Thank you! 🙏
________________________________
Van: William Lam ***@***.***>
Verzonden: Friday, September 29, 2023 7:02:19 PM
Aan: lamw/ghettoVCB ***@***.***>
CC: Werner Hellinghuizer ***@***.***>; Author ***@***.***>
Onderwerp: Re: [lamw/ghettoVCB] 8.0U2 --> ESX(i) Version not supported! (Issue #304)


Merged code and published an updated release https://github.com/lamw/ghettoVCB/releases/tag/2023_09_29
