### ISSUE TITLE
VIB-Installation on VMware ESXi 8.0.1 build-21813344 not possible - acceptance level

### ISSUE THREAD

**Issue by DVTrast** [lamw/ghettoVCB#307]
I tried to install the vib´s with the following commands:
`esxcli software vib install -v /vmfs/volumes/datastore1/vghetto-ghettoVCB.vib -f`
`esxcli software vib install -d /vmfs/volumes/datastore1/vghetto-ghettoVCB-offline-bundle.zip -f`

But the forced installation vib with both commands didn´t work because of:
`[root@localhost:/var/log] esxcli software vib install -d /vmfs/volumes/datastore1/vghetto-ghettoVCB-offline-bundle.zip -f
 [AcceptanceConfigError]
 VIB virtuallyGhetto_bootbank_ghettoVCB_1.0.0-0.0.0's acceptance level is community, which is not compliant with the ImageProfile acceptance level partner
 To change the host acceptance level, use the 'esxcli software acceptance set' command.
 Please refer to the log file for more details.`

The esx host has the standard acceptance level:
`[root@localhost:/var/log] esxcli software acceptance get
PartnerSupported`

Is there a way, to install it without changing the acceptance level?

Thank you

Best regards

Stefan Rapp

**Comment by lamw** [comment]
No, custom VIBs that aren't signed from VMware or Partners will require Community level. This is expected

**Comment by DVTrast** [comment]
Ok - thank you.
