### ISSUE TITLE
Calculated digest at EOF does not match expected result

### ISSUE THREAD

**Issue by fernan** [lamw/ghettoVCB#311]
Hi! I just downloaded vghetto 2023_09_29 and uploaded the .vib file to my ESXi 5.5 server, and when trying to install got this error: 

```
esxcli software vib install -v /vghetto-ghettoVCB.vib -f
 [InstallationError]
 Calculated digest at EOF does not match expected result: 7d3390ba046340af8b36363bcf9d8fe928c5d528f4b2b99d46215d0dce39ef84 calculated, b5a4e9f15175643f41831c57841ca8ff9897282b20aeda9f184835e32bb4b8b8 expected.
       vibs = virtuallyGhetto_bootbank_ghettoVCB_1.0.0-0.0.0
 Please refer to the log file for more details.
```

From reading other issues it is likely that I will be able to get myself going by downloading older releases perhaps. But just leave this notice here just in case it helps update something

**Comment by shyy228** [comment]
Try to install the lower version of ghettoVCB - 2021_07_09, I also guarantee the error, I used the lower version to install successfully

**Comment by enrymari** [comment]
This error occurs on versions subsequent to the 2021 versions...
I also tried the latest one, from September 2023, but the same problem occurs.
Tested on both esxi 6 and 7.
Has anyone installed the current version successfully?

**Comment by lamw** [comment]
Apologies - This is due to a change in VIB format in 8.x and while I had updated the script to build 8.x compatible VIB, I failed  to maintain a version that is also compatible with 7.x. I'll be enhancing build script to support both output going forward

**Comment by shyy228** [comment]
> This error occurs on versions subsequent to the 2021 versions... I also tried the latest one, from September 2023, but the same problem occurs. Tested on both esxi 6 and 7. Has anyone installed the current version successfully?

Hello, I failed to install the latest version on ESXI6.0. The installation of version 2021_07_09 was successful and the backup of 20 virtual hosts has been completed. Other versions have not been tested.

**Comment by shyy228** [comment]
> Apologies - This is due to a change in VIB format in 8.x and while I had updated the script to build 8.x compatible VIB, I failed to maintain a version that is also compatible with 7.x. I'll be enhancing build script to support both output going forward

Thank you for your contribution to the project and send me my most sincere blessings.
