### ISSUE TITLE
Documentation links broken since Broadcom migration

### ISSUE THREAD

**Issue by diamondsw** [lamw/ghettoVCB#316]
The links to documentation in Readme.md to [ghettoVCB Documentation](http://communities.vmware.com/docs/DOC-8760) and [ghettoVCB Restore Documentation](http://communities.vmware.com/docs/DOC-10595) are broken since the forced migration to Broadcom. Not knowing what this documentation was, I don't know if it's something you can host a archival copy of locally, or if there is a new link that can be added.

**Comment by lamw** [comment]
Looks like wayback time machine is down or else you can point to `http://communities.vmware.com/docs/DOC-8760`

Let me check if we've still got an archive version of the http://communities.vmware.com/docs/DOC-8760 or re-build that doc into github (though that may take a bit more time)

**Comment by diamondsw** [comment]
I also noticed the documentation claims the configuration files are located in `/etc`, but in my install they were also placed in `/opt` along with the main scripts. When I linked them into `/etc`, they were not picked up automatically (I still had to manually specify them with `-g`).
