### ISSUE TITLE
No config option for VM_BACKUP_DIR_NAMING_CONVENTION

### ISSUE THREAD

**Issue by mycroes** [lamw/ghettoVCB#5]
It's currently not possible to set the backup dir naming convention. Personally I'm more in favour of having this handled externally anyway, but at least permitting an override would be nice. This also interferes with the current approach to finding and deleting older backups, so this might work best in a non-rotated fashion.

**Comment by ohault** [comment]
+1

**Comment by Cescendo** [comment]
+1

**Comment by Rapitharian** [comment]
Can you provide an example of what you are looking for and what the issue is?  I would like to add this feature but I am not sure I understand exactly what you want.
