### ISSUE TITLE
Missing check for ESXi 6.0.0 in restore script

### ISSUE THREAD

**Issue by kafferejsarn** [lamw/ghettoVCB#59]
On line 96 of ghettoVCB-restore.sh there should be a check for VER6 but it is missing.
I have added the check to my script and now it is possible to restore a VM in ESXi 6.0.0.

I don't know how to clone, change and commit my changes so I only report it as an issue.

**Comment by lamw** [comment]
Thanks for the catch. I've just fixed and push the changes upstream
