### ISSUE TITLE
esxi 6.0 support

### ISSUE THREAD

**Issue by preexo** [lamw/ghettoVCB#60]
ghettoVCB is a really good piece of work! It has been quite usefull for us on esxi 5.5. Thanks for the great work!

Is ghettoVCB going to support esxi 6.0 as well?

this ticket actually seems like it does already support 6.0... https://github.com/lamw/ghettoVCB/issues/54

It's just that the documentation does not mention it anywhere. Is it safe to use yet?

**Comment by mablae** [comment]
Hey, 

I just stumbled upon this script suite. Looks very nice so far. 

@lamw  Can you please specify which ESXi versions are working?

**Comment by lamw** [comment]
Already added ESXi 6.0 support
