### ISSUE TITLE
Offline Bundle installed, and now?

### ISSUE THREAD

**Issue by Steffeng5** [lamw/ghettoVCB#62]
I currently installed the offline bundle via vib

Installation Result
   Message: Operation finished successfully.
   Reboot Required: false
   VIBs Installed: virtuallyGhetto_bootbank_ghettoVCB_1.0.0-0.0.0
   VIBs Removed:
   VIBs Skipped:

But now, I can not find any executable :-1: 

Where can I find it?

**Comment by peterhoeg** [comment]
````
/opt/ghettovcb/bin/ghettoVCB
````
