### ISSUE TITLE
Restore vm with spaces in display name

### ISSUE THREAD

**Issue by marciosouzajunior** [lamw/ghettoVCB#90]
After restore an vm with ghetto-restore, the vm is registered but cant be started, configured, etc. Also, in the datastore browse the option "Add to inventory" is disabled.
Comparing the restored .vmx file with the original, the line displayName dont contain quotes:
`displayName = Example Machine`
So putting quotes between machine name solved the problem:
`displayName = "Example Machine"`

**Comment by pkolmann** [comment]
I solved this issue, by adding the quotes into the restore.sh:

`diff --git a/ghettoVCB-restore.sh b/ghettoVCB-restore.sh
index f85100b..4f83364 100755
--- a/ghettoVCB-restore.sh
+++ b/ghettoVCB-restore.sh
@@ -286,7 +286,7 @@ if [ ! "${IS_TGZ}" == "1" ]; then
             logger "Copying \"${VM_ORIG_VMX}\" file ..."
             if [ ! "${DEVEL_MODE}" == "2" ]; then
                 cp "${VM_TO_RESTORE}/${VM_ORIG_VMX}" "${VM_RESTORE_DIR}/${VM_RESTORE_VMX}"
-                sed -i "s/displayName =.*/displayName = ${VM_DISPLAY_NAME}/g" "${VM_RESTORE_DIR}/${VM_RESTORE_VMX}"
+                sed -i "s/displayName =.*/displayName = \"${VM_DISPLAY_NAME}\"/g" "${VM_RESTORE_DIR}/${VM_RESTORE_VMX}"
             fi

             #loop through all VMDK(s) and vmkfstools copy to destination
`
