### ISSUE TITLE
NFS Mount on ESXi 6.5.0not working

### ISSUE THREAD

**Issue by linuxmonkey** [lamw/ghettoVCB#97]
Hi,
 Just for Information. in the ghettoVCB.sh (LAST_MODIFIED_DATE=2016_11_20) you have to modify line 781 from:
 if [[ ${ESX_RELEASE} == “5.5.0” ]] || [[ ${ESX_RELEASE} == “6.0.0” ]] ; then 

to:

if [[ ${ESX_RELEASE} == “5.5.0” ]] || [[ ${ESX_RELEASE} == “6.0.0” ]] || [[ ${ESX_RELEASE} == “6.5.0” ]] ; then

otherwise ESXi 6.5 host will not mount the NFS Share and you probably get an Error like:

Add a NAS datastore.
 readonly is a boolean value, 1 for readonly and 0 for rw access.
 NFS Version must be nfs for nfs v3 or nfsv41 for version 4.1 or later

**Comment by jtisch** [comment]
This fix corrected my issue:

Insufficient arguments.
Usage: nas_create name nfsVersion remotePath readonly remoteHostNames

Add a NAS datastore.
readonly is a boolean value, 1 for readonly and 0 for rw access.
     NFS Version must be nfs for nfs v3 or nfsv41 for version 4.1 or later

......

mkdir: can't create directory '/vmfs/volumes/BACKUPS/': Operation not permitted


Thank you kind sir!

**Comment by lamw** [comment]
This has been resolved with latest merge https://github.com/lamw/ghettoVCB/commit/e12a3564998eed59fce0b5c0415d371a1d4ae085
