### ISSUE TITLE
Suggestion for sending via smtp with auth plain

### ISSUE THREAD

**Issue by ggarcia** [lamw/ghettoVCB#99]
Adding the variable EMAIL_AUTH_PLAIN and the following code in line 1306 of the file ghettoVCB.sh

###
    [ "${EMAIL_AUTH_PLAIN}" != "" ] && echo -ne "AUTH PLAIN ${EMAIL_AUTH_PLAIN}\r\n" >> "${EMAIL_LOG_HEADER}"        
###

Will solve the problem of authentication when sending mail through servers that do not support relay

**Comment by lamw** [comment]
Please submit a pull request if you haven't already
